<a href="https://colab.research.google.com/github/karolrojasb/ReinasAtacerCasillasLibres/blob/main/reinasAtacarLibres.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**ME HACE FALTA HACER EL MARCAR ATAQUES Y HACER UN CONTADOR DE SOLUCIONES GLOBAL**

In [72]:
import numpy as np

In [71]:
def marcarAtaques(tablero):
  n = tablero.shape[0]
  contadorReinas = 0
  for filaR in range(n):
    for columnaR in range(n):
      if contadorReinas == n+1:
        return
      if tablero[filaR][columnaR] == 2:
        contadorReinas = contadorReinas+1
        for i in range(n):
          # Marcar ataques horizontales
          if tablero[filaR][i]==0:
            tablero[filaR][i]=1
          # Marcar ataques verticales
          if tablero[i][columnaR]==0:
            tablero[i][columnaR]=1
          # Marcar Ataques diagonales:
          if i==filaR:
            continue
          # Diagonal derecha (con pendiente negativa)
          columna = columnaR - filaR + i
          if (columna>=0) and (columna)<n:
            if tablero[i][columna]==0:
              tablero[i][columna] = 1
          # Diagonal izquierda (con pendiente positiva)
          columna = columnaR + filaR - i
          if (columna>=0) and (columna)<n:
            if tablero[i][columna]==0:
              tablero[i][columna] = 1

In [75]:
def colocarReina(tablero,filaRA,columnaRA, contadorReinas):
  exito = False # Bandera para indicar si se debe verificar el tablero
  inicio = filaRA  # variable para indicar el índice de FILA en el que se va ubicar la reina
  n = tablero.shape[0] # Obtener la dimensión del tablero
  # Si la reina anterior se puso en la última columna de una fila,
  # entonces, la nueva reina se va empezar a ubicar en la fila siguiente
  if columnaRA == n-1: # n-1 = el último índice de la columna 
    inicio = inicio + 1
  # Si la última reina era la última de el máximo de reinas,
  # entonces, todas las reinas se han ubicado y se debe verificar el tablero recibido
  if (contadorReinas == n+1): #n+1 = el máximo de reinas que se deben ubicar
    exito = True   
  # Si se ha ubicado la primera reina en la posición: penúltima fila con última columna (n-2 , n-1), 
  # quiere decir, que el resto de las reinas deben ubicarse de manera seguida, 
  # ya que de lo contrario no habrían más casillas dónde ubicarlas
  if (contadorReinas==1 and filaRA >= n-2 and columnaRA >= n-1):
    for j in range(n):
      tablero[inicio][j]=2
    exito = True
  # Si se han ubicado todas las reinas en el tablero, calcula sus ataques 
  # y verifica si es una solución valida
  if exito:
    marcarAtaques(tablero)
    if np.all(tablero):  # Retorna False si hay al menos un cero en el tablero
      print("\n ")
      print(tablero)
  else:
    for i in range(inicio,n):
      for j in range(n):
        # Cuando se debe colocar la reina en la misma fila que la anterior
        if ((j + columnaRA < 3) and (i == filaRA)):
          tablero[i][j+columnaRA+1] = 2 # Ubicar la nueva reina
          contadorReinas = contadorReinas+1 # Contar una reina ubicada
           # mandar la ubicación de la reina actual para calcular la ubicación de la siguiente
          colocarReina(tablero,i,j+columnaRA+1,contadorReinas)
          # Desmarcar la reina actual para que en el otro ciclo de los for anidados se pruebe
          # con la siguiente posición disponible
          tablero[i][(j+columnaRA+1)] = 0  
          # descontador la reina desmarcada
          contadorReinas = contadorReinas - 1
        else:
          # Para ubicar la reina en todas las columnas desde la primera con índice 0
          # hasta la última, pero en la fila o filas siguientes a la de la reina anterior
          if (i>filaRA): 
            tablero[i][j] = 2 # Ubicar la nueva reina
            contadorReinas = contadorReinas+1 # Contar una reina ubicada
            # mandar la ubicación de la reina actual para calcular la ubicación de la siguiente
            colocarReina(tablero,i,j,contadorReinas) 
            # Desmarcar la reina actual para que en el otro ciclo de los for anidados se pruebe
            # con la siguiente posición disponible
            tablero[i][j] = 0
            # descontador la reina desmarcada
            contadorReinas = contadorReinas-1

In [69]:
# Función ue encuentra todas las soluciones posibles de como ubicar, en un tablero de nxn, n + 1 reinas de tal forma
# que todas las casillas del tablero queden atacadas.
# En el tablero:
# - Un CERO indica que es un espacio libre y NO atacado
# - Un UNO indica que es un espacio libreo PERO SÍ esta siendo atacado
# - Un DOS indica que es un espacio OCUPADO por una reina

def reinasAtacarLibres(dimensionTablero):
  tablero = np.zeros((dimensionTablero,dimensionTablero),dtype=np.uint8) #Tablero lleno de ceros
  numReinas=dimensionTablero+1
  contadorReinas=0
  for i in range (tablero.shape[0]-1): ## Nunca se ubica una primera reina en la última fila de la matriz
    for j in range (tablero.shape[0]):
      tablero[i][j] = 2 # colocar primera reina
      contadorReinas = contadorReinas+1
      colocarReinas(tablero,i,j,numReinas,contadorReinas)  
      tablero[i][j] = 0
      contadorReinas=contadorReinas-1

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 2 2 1 1 1 1]
 [2 2 2 1 1 1 1 1]
 [1 2 2 1 1 1 1 1]
 [1 1 1 1 1 2 1 1]
 [1 1 1 1 2 1 1 1]]
